Repository symfony/symfony, pull requests merged in 2019-08, with the labels that each got.

#32846 [PhpUnitBridge] Fix deprecation assertInternalType
  src/Symfony/Bridge/Doctrine/Tests/Form/Type/EntityTypeTest.php
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/SerializerCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/ValidatorCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ProfilerTest.php
  src/Symfony/Component/Config/Tests/Definition/Builder/TreeBuilderTest.php
  src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php
  src/Symfony/Component/DependencyInjection/Tests/Loader/YamlFileLoaderTest.php
  src/Symfony/Component/DependencyInjection/Tests/ParameterBag/EnvPlaceholderParameterBagTest.php
  src/Symfony/Component/DomCrawler/Tests/CrawlerTest.php
  src/Symfony/Component/DomCrawler/Tests/Field/FileFormFieldTest.php
  src/Symfony/Component/Form/Tests/Extension/DataCollector/DataCollectorExtensionTest.php
  src/Symfony/Component/Form/Tests/Extension/Validator/Type/BaseValidatorExtensionTest.php
  src/Symfony/Component/HttpFoundation/Tests/JsonResponseTest.php
  src/Symfony/Component/HttpFoundation/Tests/RequestTest.php
  src/Symfony/Component/HttpFoundation/Tests/Session/Storage/NativeSessionStorageTest.php
  src/Symfony/Component/HttpKernel/Tests/DataCollector/MemoryDataCollectorTest.php
  src/Symfony/Component/Intl/Tests/Data/Bundle/Reader/JsonBundleReaderTest.php
  src/Symfony/Component/Intl/Tests/Data/Bundle/Reader/PhpBundleReaderTest.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractCurrencyDataProviderTest.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/NumberFormatterTest.php
  src/Symfony/Component/Process/Tests/ProcessTest.php
  src/Symfony/Component/Routing/Tests/Matcher/UrlMatcherTest.php
  src/Symfony/Component/Security/Http/Tests/RememberMe/AbstractRememberMeServicesTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/AbstractObjectNormalizerTest.php
  src/Symfony/Component/Stopwatch/Tests/StopwatchTest.php
  src/Symfony/Component/VarDumper/Tests/Cloner/DataTest.php
  src/Symfony/Component/Yaml/Tests/ParserTest.php
Labels: Bug, PhpUnitBridge, Status: Needs Review

#32849 [TwigBridge] revert added type declarations
  src/Symfony/Bridge/Twig/Command/DebugCommand.php
  src/Symfony/Bridge/Twig/Command/LintCommand.php
  src/Symfony/Bridge/Twig/DataCollector/TwigDataCollector.php
  src/Symfony/Bridge/Twig/NodeVisitor/TranslationDefaultDomainNodeVisitor.php
Labels: Status: Needs Review, TwigBridge

#32851 Sync UPGRADE-5.0.md
  UPGRADE-5.0.md
Labels: Status: Needs Review

#32854 Ensure signatures for setUp|tearDown|setUpAfterClass|tearDownAfterClass methods in tests are compatible with phpunit 8.2
  src/Symfony/Bridge/Doctrine/Tests/Messenger/DoctrineCloseConnectionMiddlewareTest.php
  src/Symfony/Bridge/Doctrine/Tests/Messenger/DoctrinePingConnectionMiddlewareTest.php
  src/Symfony/Bridge/Doctrine/Tests/Messenger/DoctrineTransactionMiddlewareTest.php
  src/Symfony/Bridge/PhpUnit/Tests/ClassExistsMockTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/CachePoolDeleteCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/XliffLintCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolListCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/RouterDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/TranslationDebugCommandTest.php
  src/Symfony/Component/Cache/Tests/Adapter/PredisTagAwareAdapterTest.php
  src/Symfony/Component/Cache/Tests/Adapter/PredisTagAwareClusterAdapterTest.php
  src/Symfony/Component/Cache/Tests/Adapter/PredisTagAwareRedisClusterAdapterTest.php
  src/Symfony/Component/Cache/Tests/Adapter/RedisTagAwareAdapterTest.php
  src/Symfony/Component/Cache/Tests/Adapter/RedisTagAwareArrayAdapterTest.php
  src/Symfony/Component/Cache/Tests/Adapter/RedisTagAwareClusterAdapterTest.php
  src/Symfony/Component/Cache/Tests/DependencyInjection/CachePoolPassTest.php
  src/Symfony/Component/Cache/Tests/Psr16CacheTest.php
  src/Symfony/Component/Console/Tests/Helper/DumperNativeFallbackTest.php
  src/Symfony/Component/Console/Tests/Helper/DumperTest.php
  src/Symfony/Component/Console/Tests/Output/ConsoleSectionOutputTest.php
  src/Symfony/Component/Console/Tests/Question/QuestionTest.php
  src/Symfony/Component/DependencyInjection/Tests/ParameterBag/ContainerBagTest.php
  src/Symfony/Component/EventDispatcher/Tests/EventDispatcherTest.php
  src/Symfony/Component/Form/Tests/ChoiceList/Loader/IntlCallbackChoiceLoaderTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/StringToFloatTransformerTest.php
  src/Symfony/Component/HttpClient/Tests/Psr18ClientTest.php
  src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MigratingSessionHandlerTest.php
  src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/RedisClusterSessionHandlerTest.php
  src/Symfony/Component/HttpKernel/Tests/EventListener/LocaleAwareListenerTest.php
  src/Symfony/Component/Lock/Tests/Store/PdoDbalStoreTest.php
  src/Symfony/Component/Lock/Tests/Store/PdoStoreTest.php
  src/Symfony/Component/Messenger/Tests/Command/DebugCommandTest.php
  src/Symfony/Component/Messenger/Tests/DataCollector/MessengerDataCollectorTest.php
  src/Symfony/Component/Messenger/Tests/Transport/AmqpExt/AmqpExtIntegrationTest.php
  src/Symfony/Component/Messenger/Tests/Transport/InMemoryTransportFactoryTest.php
  src/Symfony/Component/Messenger/Tests/Transport/InMemoryTransportTest.php
  src/Symfony/Component/Messenger/Tests/Transport/RedisExt/RedisExtIntegrationTest.php
  src/Symfony/Component/Mime/Tests/AbstractMimeTypeGuesserTest.php
  src/Symfony/Component/Routing/Tests/Generator/Dumper/CompiledUrlGeneratorDumperTest.php
  src/Symfony/Component/Routing/Tests/Matcher/Dumper/CompiledUrlMatcherDumperTest.php
  src/Symfony/Component/Security/Core/Tests/Encoder/SodiumPasswordEncoderTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/ConstraintViolationListNormalizerTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/DateTimeZoneNormalizerTest.php
  src/Symfony/Component/Translation/Tests/Command/XliffLintCommandTest.php
  src/Symfony/Component/VarDumper/Tests/Command/Descriptor/CliDescriptorTest.php
  src/Symfony/Component/VarDumper/Tests/Command/Descriptor/HtmlDescriptorTest.php
  src/Symfony/Component/Workflow/Tests/Metadata/InMemoryMetadataStoreTest.php
  src/Symfony/Component/Yaml/Tests/ParserTest.php
Labels: Feature, Status: Reviewed

#32857 [PhpUnitBridge] Fix deprecation assertInternalType - 4.3
  src/Symfony/Component/Intl/Tests/CurrenciesTest.php
  src/Symfony/Component/Workflow/Tests/RegistryTest.php
Labels: Bug, PhpUnitBridge, Status: Needs Review

#32858 [PhpUnitBridge] Fix deprecation assertInternalType - 4.4
  src/Symfony/Component/HttpClient/Tests/HttpClientTestCase.php
Labels: Bug, PhpUnitBridge, Status: Needs Review

#32864 Skip tests that fatal-error on PHP 7.4 because of missing parent classes
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/ValidatorCacheWarmerTest.php
  src/Symfony/Component/Config/Tests/Resource/ClassExistenceResourceTest.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveBindingsPassTest.php
  src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php
  src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php
Labels: Status: Needs Review

#32865 Add polyfill for TestCase::createMock()
  src/Symfony/Bridge/PhpUnit/ForwardCompatTestTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV7.php
  src/Symfony/Component/Validator/Tests/DataCollector/ValidatorDataCollectorTest.php
  src/Symfony/Component/Validator/Tests/Validator/TraceableValidatorTest.php
Labels: Status: Needs Review

#32866 Sync "not implementing the method" deprecations messages
  src/Symfony/Component/Config/Definition/Builder/NodeDefinition.php
  src/Symfony/Component/Form/AbstractExtension.php
  src/Symfony/Component/Form/DependencyInjection/FormPass.php
  src/Symfony/Component/Form/PreloadedExtension.php
  src/Symfony/Component/Security/Core/Authentication/Token/Storage/TokenStorage.php
  src/Symfony/Component/Security/Core/Authorization/Voter/ExpressionVoter.php
  src/Symfony/Component/Security/Core/Authorization/Voter/RoleHierarchyVoter.php
  src/Symfony/Component/Security/Core/Authorization/Voter/RoleVoter.php
  src/Symfony/Component/Workflow/EventListener/GuardListener.php
Labels: Status: Needs Review

#32867 [TwigBundle] Twig's namespaces can be null
  src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php
Labels: Bug, Status: Reviewed, TwigBundle

#32868 [PhpUnitBridge] Allow symfony/phpunit-bridge > 4.2 to be installed with phpunit 4.8
  src/Symfony/Bridge/PhpUnit/bin/simple-phpunit
Labels: Bug, PhpUnitBridge, Status: Needs Review

#32871 bump required PHP versions
  src/Symfony/Component/ErrorHandler/composer.json
  src/Symfony/Component/ErrorRenderer/composer.json
Labels: ErrorHandler, ErrorRenderer, Status: Reviewed

#32504 [ErrorRenderer] Add DebugCommand for easy debugging and testing
  src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
  src/Symfony/Component/ErrorRenderer/Command/DebugCommand.php
  src/Symfony/Component/ErrorRenderer/DependencyInjection/ErrorRendererPass.php
  src/Symfony/Component/ErrorRenderer/Tests/Command/DebugCommandTest.php
  src/Symfony/Component/ErrorRenderer/composer.json
Labels: ErrorRenderer, Feature, Status: Reviewed

#32817 [DoctrineBridge] Deprecate RegistryInterface
  UPGRADE-4.4.md
  UPGRADE-5.0.md
  src/Symfony/Bridge/Doctrine/CHANGELOG.md
  src/Symfony/Bridge/Doctrine/RegistryInterface.php
Labels: Deprecation, DoctrineBridge, Status: Reviewed

#32869 [PhpUnitBridge] Add polyfill for expectException* methods
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
Labels: Feature, PhpUnitBridge, Status: Reviewed

#32859 [TwigBridge] add parameter type declarations to private methods
  src/Symfony/Bridge/Twig/Command/DebugCommand.php
  src/Symfony/Bridge/Twig/Command/LintCommand.php
  src/Symfony/Bridge/Twig/DataCollector/TwigDataCollector.php
  src/Symfony/Bridge/Twig/NodeVisitor/TranslationDefaultDomainNodeVisitor.php
Labels: Status: Reviewed, TwigBridge

#32876 [DoctrineBridge] Removed RegistryInterface
  src/Symfony/Bridge/Doctrine/RegistryInterface.php
Labels: BC Break, DoctrineBridge, Status: Reviewed

#32887 Run the phpunit-bridge from a PR
  .gitignore
  .travis.yml
  src/Symfony/Bridge/PhpUnit/ForwardCompatTestTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV7.php
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV8.php
Labels: Status: Reviewed

#32893 [PhpUnitBridge] Polyfill the method createPartialMock
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
Labels: Feature, PhpUnitBridge, Status: Needs Review

#32894 [Mailer] Change the order of authenticators
  src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php
Labels: Mailer, Status: Needs Review

#32895 [Mailer] Fix error not being thrown properly
  src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php
Labels: Bug, Mailer, Status: Needs Review

#32896 [Mailer] added debug info to TransportExceptionInterface
  src/Symfony/Component/Mailer/Exception/TransportException.php
  src/Symfony/Component/Mailer/Exception/TransportExceptionInterface.php
  src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php
Labels: Feature, Mailer, Status: Needs Review

#32899 [Mailer] fix wrong error message when connection closes unexpectedly
  src/Symfony/Component/Mailer/Transport/Smtp/Stream/AbstractStream.php
Labels: Bug, Status: Needs Review

#32886 [PhpUnitBridge] Add polyfill for methods assertNan, assertFinite and assertInfinite
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
Labels: Bug, Feature, Status: Needs Review

#32885 [PhpUnitBridge] Use PHPUnit75Migration in CS fixer
  .php_cs.dist
  src/Symfony/Component/Console/Tests/Logger/ConsoleLoggerTest.php
  src/Symfony/Component/Debug/Tests/Exception/FlattenExceptionTest.php
  src/Symfony/Component/DependencyInjection/ContainerBuilder.php
  src/Symfony/Component/DependencyInjection/Tests/ContainerTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/DataTransformer/NumberToLocalizedStringTransformerTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/ButtonTypeTest.php
  src/Symfony/Component/HttpKernel/Tests/Log/LoggerTest.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/TimezoneTransformer.php
  src/Symfony/Component/Lock/Tests/Store/ExpiringStoreTestTrait.php
  src/Symfony/Component/Yaml/Tests/ParserTest.php
Labels: Bug, PhpUnitBridge, Status: Needs Review

#32892 [Validator] Improve Fa translations
  src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf
Labels: Bug, Status: Reviewed, Validator

#32905 [PhpUnitBridge] cleanup implementation of expectException*()
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
Labels: PhpUnitBridge, Status: Needs Review

#32878 [PhpUnitBridge] added polyfill for assertStringContainsString*()
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
Labels: Feature, Status: Needs Review

#32907 [PhpUnitBridge] add more assert*() polyfills
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV5.php
Labels: PhpUnitBridge, Status: Needs Review

#32908 [Mailer] Add debug info on HTTP transport exceptions
  src/Symfony/Component/Mailer/Transport/AbstractHttpTransport.php
Labels: Bug, Mailer, Status: Needs Review

#32870 #32853 Check if $this->parameters is array.
  src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
Labels: Bug, DependencyInjection, Status: Needs Review

#32909 [PhpUnitBridge] Remove deprecated methods assertArraySubset
  src/Symfony/Bundle/SecurityBundle/Tests/Functional/JsonLoginTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/JsonSerializableNormalizerTest.php
Labels: Bug, PhpUnitBridge, Status: Needs Review

#32882 [PhpUnitBridge] Inject ForwardCompatibiliy in TestCase
  src/Symfony/Bridge/PhpUnit/Legacy/ForwardCompatTestTraitForV7.php
  src/Symfony/Bridge/PhpUnit/Legacy/PolyfillAssertTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/PolyfillTestCaseTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/SetUpTearDownTraitForV5.php
  src/Symfony/Bridge/PhpUnit/Legacy/SetUpTearDownTraitForV8.php
  src/Symfony/Bridge/PhpUnit/SetUpTearDownTrait.php
  src/Symfony/Bridge/PhpUnit/Tests/ClockMockTest.php
  src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php
Labels: Feature, PhpUnitBridge, Status: Reviewed

#32913 [travis] Fix path to phpunit binary
  .travis.yml
Labels: Bug, Status: Needs Review

#32910 [Yaml] PHP-8: Uncaught TypeError: abs() expects parameter 1 to be int or float, string given
  src/Symfony/Component/Yaml/Parser.php
  src/Symfony/Component/Yaml/Tests/ParserTest.php
Labels: Bug, Status: Reviewed, Yaml

#32682 [HttpFoundation] Revert getClientIp @return docblock
  src/Symfony/Component/HttpFoundation/Request.php
Labels: Bug, HttpFoundation, Status: Reviewed

#32669 [Yaml] Add flag to dump NULL as ~
  src/Symfony/Component/Yaml/CHANGELOG.md
  src/Symfony/Component/Yaml/Inline.php
  src/Symfony/Component/Yaml/Tests/DumperTest.php
  src/Symfony/Component/Yaml/Yaml.php
Labels: Feature, Status: Reviewed, Yaml

#32917 [Mime] Add AbstractPart::asDebugString()
  src/Symfony/Component/Mime/CHANGELOG.md
  src/Symfony/Component/Mime/Part/AbstractMultipartPart.php
  src/Symfony/Component/Mime/Part/AbstractPart.php
  src/Symfony/Component/Mime/Part/DataPart.php
  src/Symfony/Component/Mime/Part/TextPart.php
Labels: Feature, Mime, Status: Needs Review

#32916 [Mailer] Add a name to the transports
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/MailerTest.php
  src/Symfony/Bundle/FrameworkBundle/composer.json
  src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiTransport.php
  src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesHttpTransport.php
  src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillApiTransport.php
  src/Symfony/Component/Mailer/Bridge/Mailchimp/Transport/MandrillHttpTransport.php
  src/Symfony/Component/Mailer/Bridge/Mailgun/Transport/MailgunApiTransport.php
  src/Symfony/Component/Mailer/Bridge/Mailgun/Transport/MailgunHttpTransport.php
  src/Symfony/Component/Mailer/Bridge/Postmark/Transport/PostmarkApiTransport.php
  src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridApiTransport.php
  src/Symfony/Component/Mailer/CHANGELOG.md
  src/Symfony/Component/Mailer/Test/TransportFactoryTestCase.php
  src/Symfony/Component/Mailer/Tests/Transport/FailoverTransportTest.php
  src/Symfony/Component/Mailer/Tests/Transport/NullTransportTest.php
  src/Symfony/Component/Mailer/Tests/Transport/RoundRobinTransportTest.php
  src/Symfony/Component/Mailer/Tests/Transport/SendmailTransportTest.php
  src/Symfony/Component/Mailer/Tests/Transport/Smtp/SmtpTransportTest.php
  src/Symfony/Component/Mailer/Tests/TransportTest.php
  src/Symfony/Component/Mailer/Transport/AbstractTransport.php
  src/Symfony/Component/Mailer/Transport/FailoverTransport.php
  src/Symfony/Component/Mailer/Transport/NullTransport.php
  src/Symfony/Component/Mailer/Transport/RoundRobinTransport.php
  src/Symfony/Component/Mailer/Transport/SendmailTransport.php
  src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php
  src/Symfony/Component/Mailer/Transport/TransportInterface.php
Labels: Feature, Mailer, Status: Needs Review

#32920 [PhpUnitBridge] fix internal annotation
  src/Symfony/Bridge/PhpUnit/Legacy/PolyfillAssertTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/PolyfillTestCaseTrait.php
  src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php
Labels: PhpUnitBridge, Status: Needs Review

#32915 [Routing] Add a warning about the getRouteCollection() method
  src/Symfony/Component/Routing/RouterInterface.php
Labels: Routing, Status: Reviewed

#32814 Create mailBody with only attachments part present
  src/Symfony/Component/Mime/Email.php
  src/Symfony/Component/Mime/Tests/EmailTest.php
Labels: Bug, Mailer, Status: Reviewed

#32923 [PhpUnitBridge] Remove calls to deprecated function assertAttributeX
  src/Symfony/Component/EventDispatcher/Tests/GenericEventTest.php
  src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/PdoSessionHandlerTest.php
Labels: Bug, PhpUnitBridge, Status: Reviewed

#32902 [PhpUnitBridge] Allow sutFqcnResolver to return array
  src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php
Labels: Bug, Status: Reviewed

#32927 [Mailer] Add message events logger
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  src/Symfony/Bundle/FrameworkBundle/Resources/config/mailer_debug.xml
  src/Symfony/Component/Mailer/CHANGELOG.md
  src/Symfony/Component/Mailer/Event/MessageEvent.php
  src/Symfony/Component/Mailer/Event/MessageEvents.php
  src/Symfony/Component/Mailer/EventListener/MessageLoggerListener.php
  src/Symfony/Component/Mailer/Mailer.php
  src/Symfony/Component/Mailer/Transport/AbstractTransport.php
  src/Symfony/Component/Mailer/composer.json
Labels: Feature, Status: Reviewed

#32931 [PhpUnitBridge] Polyfill assertion method on Filesystem
  src/Symfony/Bridge/PhpUnit/Legacy/PolyfillAssertTrait.php
Labels: Feature, PhpUnitBridge, Status: Reviewed

#32918 [Intl] Order alpha2 to alpha3 mapping
  src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php
  src/Symfony/Component/Intl/Resources/data/languages/meta.json
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractLanguageDataProviderTest.php
Labels: Bug, Intl, Status: Reviewed

#32873 [ErrorRenderer] Add alias to FlattenException to avoid BC break
  src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php
Labels: Bug, ErrorRenderer, Status: Reviewed

#32934 [Form] type cannot be a FormTypeInterface anymore
  src/Symfony/Component/Form/ButtonBuilder.php
  src/Symfony/Component/Form/Form.php
  src/Symfony/Component/Form/FormBuilder.php
  src/Symfony/Component/Form/Tests/FormBuilderTest.php
Labels: Form, Status: Reviewed

#32838 [FrameworkBundle] Detect indirect env vars in routing
  src/Symfony/Bundle/FrameworkBundle/Routing/Router.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Routing/RouterTest.php
Labels: Bug, FrameworkBundle, Status: Reviewed

#32836 [Messenger] Removed named parameters and replaced with `?` placeholders for sqlsrv compatibility
  src/Symfony/Component/Messenger/Transport/Doctrine/Connection.php
Labels: Bug, Messenger, Status: Reviewed

#32922 [PhpUnitBridge] make the bridge act as a polyfill for newest PHPUnit features
  src/Symfony/Bridge/PhpUnit/CHANGELOG.md
Labels: Feature, PhpUnitBridge, Status: Reviewed

#32792 [Messenger] Fix incompatibility with FrameworkBundle <4.3.1
  src/Symfony/Bundle/FrameworkBundle/Resources/config/console.xml
  src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php
  src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php
Labels: Bug, Messenger, Status: Reviewed

#32928 [HttpClient] use "idle" instead of "inactivity" when telling about the timeout option
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
  src/Symfony/Component/HttpClient/Chunk/ErrorChunk.php
  src/Symfony/Contracts/HttpClient/ChunkInterface.php
  src/Symfony/Contracts/HttpClient/HttpClientInterface.php
Labels: HttpClient, Status: Reviewed

#32924 [cs-fixer] Use PhpUnit native assertions in filsystem checks
  .php_cs.dist
  src/Symfony/Component/Filesystem/Tests/FilesystemTest.php
  src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/NativeFileSessionHandlerTest.php
  src/Symfony/Component/Intl/Tests/IntlTest.php
  src/Symfony/Component/Intl/Tests/Util/GitRepositoryTest.php
Labels: Status: Reviewed

#32919 [Intl] Order alpha2 to alpha3 mapping + phpdoc fixes
  src/Symfony/Component/Intl/Countries.php
  src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php
  src/Symfony/Component/Intl/Languages.php
  src/Symfony/Component/Intl/Locales.php
  src/Symfony/Component/Intl/Resources/data/languages/meta.json
  src/Symfony/Component/Intl/Scripts.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractLanguageDataProviderTest.php
  src/Symfony/Component/Intl/Tests/LanguagesTest.php
Labels: Bug, Intl, Status: Reviewed

#32938 [Lock] Legacy test should implement legacy interface
  src/Symfony/Component/Lock/Tests/LockTest.php
Labels: Lock, Status: Reviewed

#32939 [Security] remove the deprecated LdapUserProvider class
  src/Symfony/Component/Security/CHANGELOG.md
  src/Symfony/Component/Security/Core/Tests/User/LdapUserProviderTest.php
  src/Symfony/Component/Security/Core/User/LdapUserProvider.php
Labels: BC Break, Security, Status: Reviewed

#32944 [Yaml] Removed unused $nullAsTilde property
  src/Symfony/Component/Yaml/Inline.php
Labels: Bug, Status: Needs Review, Yaml

#32942 [Ldap] Fix LdapUserProvider signatures
  src/Symfony/Component/Ldap/Security/LdapUserProvider.php
  src/Symfony/Component/Ldap/composer.json
Labels: Ldap, Status: Reviewed

#31843 [Security] add support for opportunistic password migrations
  src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php
  src/Symfony/Bridge/Doctrine/Tests/Security/User/EntityUserProviderTest.php
  src/Symfony/Bridge/Doctrine/composer.json
  src/Symfony/Bundle/SecurityBundle/Resources/config/guard.xml
  src/Symfony/Component/Ldap/Security/LdapUserProvider.php
  src/Symfony/Component/Security/CHANGELOG.md
  src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php
  src/Symfony/Component/Security/Core/Tests/Authentication/Provider/DaoAuthenticationProviderTest.php
  src/Symfony/Component/Security/Core/Tests/Encoder/MigratingPasswordEncoderTest.php
  src/Symfony/Component/Security/Core/Tests/Encoder/TestPasswordEncoderInterface.php
  src/Symfony/Component/Security/Core/Tests/User/ChainUserProviderTest.php
  src/Symfony/Component/Security/Core/User/ChainUserProvider.php
  src/Symfony/Component/Security/Core/User/PasswordUpgraderInterface.php
  src/Symfony/Component/Security/Guard/PasswordAuthenticatedInterface.php
  src/Symfony/Component/Security/Guard/Provider/GuardAuthenticationProvider.php
Labels: Feature, Ready, Security, Status: Reviewed

#32946 [Messenger] Fixed ConsumeMessagesCommand configuration
  src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php
Labels: Messenger, Status: Reviewed

#32949 [Form] remove leftover int child phpdoc
  src/Symfony/Component/Form/Button.php
Labels: Form, Status: Reviewed

#32940 [PhpUnitBridge] Add polyfill for PhpUnit namespace
  src/Symfony/Bridge/PhpUnit/CHANGELOG.md
  src/Symfony/Bridge/PhpUnit/CoverageListener.php
  src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php
  src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler/Deprecation.php
  src/Symfony/Bridge/PhpUnit/Legacy/CoverageListenerTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/PolyfillTestCaseTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php
  src/Symfony/Bridge/PhpUnit/SymfonyTestsListener.php
  src/Symfony/Bridge/PhpUnit/Tests/Fixtures/coverage/tests/bootstrap.php
  src/Symfony/Bridge/PhpUnit/Tests/ProcessIsolationTest.php
  src/Symfony/Bridge/PhpUnit/TextUI/Command.php
  src/Symfony/Bridge/PhpUnit/bootstrap.php
Labels: Feature, PhpUnitBridge, Status: Reviewed

#32941 Use namespaced Phpunit classes
  .travis.yml
  src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveInstanceofConditionalsPassTest.php
  src/Symfony/Component/DependencyInjection/Tests/Config/ContainerParametersResourceCheckerTest.php
  src/Symfony/Component/Form/Tests/Resources/TranslationFilesTest.php
  src/Symfony/Component/HttpKernel/Tests/DependencyInjection/RemoveEmptyControllerArgumentLocatorsPassTest.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php
  src/Symfony/Component/Security/Core/Tests/Resources/TranslationFilesTest.php
  src/Symfony/Component/Validator/Tests/Resources/TranslationFilesTest.php
  src/Symfony/Component/Yaml/Tests/ParserTest.php
Labels: Bug, Status: Reviewed

#32947 [Intl] Support DateTimeInterface in IntlDateFormatter::format
  src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php
  src/Symfony/Component/Intl/Tests/DateFormatter/AbstractIntlDateFormatterTest.php
Labels: Bug, Intl, Status: Reviewed

#32933 [PhpUnitBridge] fixed PHPUnit 8.3 compatibility: method handleError was renamed to __invoke
  src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php
Labels: Bug, Status: Reviewed

#32948 [HttpClient] Minor fixes
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
  src/Symfony/Component/HttpClient/Response/MockResponse.php
  src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
Labels: Bug, HttpClient, Status: Needs Review

#32951 [Mailer] Fix dispatcher not available in Mailer
  src/Symfony/Bundle/FrameworkBundle/Resources/config/mailer.xml
  src/Symfony/Component/Mailer/Mailer.php
Labels: Bug, Mailer, Status: Needs Review

#32935 [Form] Fix inconsistencies
  src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php
  src/Symfony/Component/Form/ChoiceList/Factory/ChoiceListFactoryInterface.php
  src/Symfony/Component/Form/ChoiceList/View/ChoiceView.php
Labels: Bug, Form, Status: Reviewed

#32954 Use PHPUnit short class name in tests comments
  src/Symfony/Bridge/Doctrine/Tests/Form/ChoiceList/DoctrineChoiceLoaderTest.php
  src/Symfony/Bridge/Doctrine/Tests/Form/Type/EntityTypeTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/AnnotationsCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/CachePruneCommandTest.php
  src/Symfony/Component/Cache/Tests/Adapter/ChainAdapterTest.php
  src/Symfony/Component/Cache/Tests/Adapter/TagAwareAdapterTest.php
  src/Symfony/Component/Cache/Tests/Simple/ChainCacheTest.php
  src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php
  src/Symfony/Component/EventDispatcher/Tests/ImmutableEventDispatcherTest.php
  src/Symfony/Component/Form/Tests/AbstractFormTest.php
  src/Symfony/Component/Form/Tests/ChoiceList/Factory/CachingFactoryDecoratorTest.php
  src/Symfony/Component/Form/Tests/ChoiceList/Factory/PropertyAccessDecoratorTest.php
  src/Symfony/Component/Form/Tests/ChoiceList/LazyChoiceListTest.php
  src/Symfony/Component/Form/Tests/Extension/Csrf/Type/FormTypeCsrfExtensionTest.php
  src/Symfony/Component/Form/Tests/Extension/DataCollector/DataCollectorExtensionTest.php
  src/Symfony/Component/Form/Tests/Extension/DataCollector/FormDataCollectorTest.php
  src/Symfony/Component/Form/Tests/Extension/DataCollector/FormDataExtractorTest.php
  src/Symfony/Component/Form/Tests/Extension/DataCollector/Type/DataCollectorTypeExtensionTest.php
  src/Symfony/Component/Form/Tests/FormFactoryTest.php
  src/Symfony/Component/Form/Tests/FormRegistryTest.php
  src/Symfony/Component/Form/Tests/ResolvedFormTypeTest.php
  src/Symfony/Component/HttpFoundation/Tests/Session/Storage/Handler/MongoDbSessionHandlerTest.php
  src/Symfony/Component/Intl/Tests/Data/Bundle/Reader/BundleEntryReaderTest.php
  src/Symfony/Component/Ldap/Tests/LdapClientTest.php
  src/Symfony/Component/Ldap/Tests/LdapTest.php
  src/Symfony/Component/Lock/Tests/Store/CombinedStoreTest.php
  src/Symfony/Component/Serializer/Tests/Encoder/XmlEncoderTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/AbstractNormalizerTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/ArrayDenormalizerTest.php
  src/Symfony/Component/Serializer/Tests/Normalizer/JsonSerializableNormalizerTest.php
  src/Symfony/Component/Translation/Tests/TranslatorCacheTest.php
Labels: Bug, Status: Reviewed

#32912 [Mailer] Add support for the profiler
  src/Symfony/Bundle/FrameworkBundle/Resources/config/mailer_debug.xml
  src/Symfony/Bundle/WebProfilerBundle/CHANGELOG.md
  src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/mailer.html.twig
  src/Symfony/Bundle/WebProfilerBundle/Resources/views/Icon/mailer.svg
  src/Symfony/Component/Mailer/CHANGELOG.md
  src/Symfony/Component/Mailer/DataCollector/MessageDataCollector.php
  src/Symfony/Component/Mailer/Event/MessageEvents.php
Labels: Feature, Mailer, Status: Reviewed

#32930 [Mailer][Mime] Add PHPUnit constraints and assertions for the Mailer
  src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  src/Symfony/Bundle/FrameworkBundle/Test/MailerAssertionsTrait.php
  src/Symfony/Bundle/FrameworkBundle/Test/WebTestAssertionsTrait.php
  src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/Bundle/TestBundle/Controller/EmailController.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/MailerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/app/Mailer/config.yml
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/app/Mailer/routing.yml
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/app/Mailer/services.yml
  src/Symfony/Bundle/FrameworkBundle/composer.json
  src/Symfony/Component/Mailer/CHANGELOG.md
  src/Symfony/Component/Mailer/Test/Constraint/EmailCount.php
  src/Symfony/Component/Mailer/Test/Constraint/EmailIsQueued.php
  src/Symfony/Component/Mime/CHANGELOG.md
  src/Symfony/Component/Mime/Test/Constraint/EmailAddressContains.php
  src/Symfony/Component/Mime/Test/Constraint/EmailAttachmentCount.php
  src/Symfony/Component/Mime/Test/Constraint/EmailHasHeader.php
  src/Symfony/Component/Mime/Test/Constraint/EmailHeaderSame.php
  src/Symfony/Component/Mime/Test/Constraint/EmailHtmlBodyContains.php
  src/Symfony/Component/Mime/Test/Constraint/EmailTextBodyContains.php
Labels: Feature, Mailer, Mime, Status: Needs Review

#32958 [Mailer] Make the message logger permanent
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  src/Symfony/Bundle/FrameworkBundle/Resources/config/mailer.xml
  src/Symfony/Bundle/FrameworkBundle/Resources/config/mailer_debug.xml
Labels: Bug, Status: Needs Review

#32966 [ErrorHandler][ErrorRenderer] Fix branch aliases
  src/Symfony/Component/ErrorHandler/composer.json
  src/Symfony/Component/ErrorRenderer/composer.json
Labels: Bug, ErrorRenderer, Status: Reviewed

#32972 [PHPUnitBridge] Fix name of logical classes
  src/Symfony/Bridge/PhpUnit/bootstrap.php
Labels: Bug, PhpUnitBridge, Status: Reviewed

#32971 Use assertStringContainsString when needed
  src/Symfony/Bridge/Monolog/Tests/Handler/ConsoleHandlerTest.php
  src/Symfony/Bridge/PhpUnit/Tests/CoverageListenerTest.php
  src/Symfony/Bridge/Twig/Tests/Command/DebugCommandTest.php
  src/Symfony/Bridge/Twig/Tests/Command/LintCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/RouterDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/RouterMatchCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/TranslationDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/TranslationUpdateCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/YamlLintCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Console/ApplicationTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerNameParserTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTraitTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolClearCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ConfigDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ConfigDumpReferenceCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/DebugAutowiringCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/SessionTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Templating/Loader/TemplateLocatorTest.php
  src/Symfony/Bundle/SecurityBundle/Tests/Functional/CsrfFormLoginTest.php
  src/Symfony/Bundle/SecurityBundle/Tests/Functional/FormLoginTest.php
  src/Symfony/Bundle/SecurityBundle/Tests/Functional/UserPasswordEncoderCommandTest.php
  src/Symfony/Bundle/TwigBundle/Tests/Functional/NoTemplatingEntryTest.php
  src/Symfony/Component/Config/Tests/Fixtures/Resource/.hiddenFile
  src/Symfony/Component/Config/Tests/Util/XmlUtilsTest.php
  src/Symfony/Component/Console/Tests/ApplicationTest.php
  src/Symfony/Component/Console/Tests/Command/CommandTest.php
  src/Symfony/Component/Console/Tests/Command/HelpCommandTest.php
  src/Symfony/Component/Console/Tests/Formatter/OutputFormatterStyleTest.php
  src/Symfony/Component/Console/Tests/Helper/HelperSetTest.php
  src/Symfony/Component/Console/Tests/Helper/QuestionHelperTest.php
  src/Symfony/Component/Console/Tests/Helper/SymfonyQuestionHelperTest.php
  src/Symfony/Component/Debug/Tests/Exception/FlattenExceptionTest.php
  src/Symfony/Component/Debug/Tests/ExceptionHandlerTest.php
  src/Symfony/Component/DependencyInjection/Tests/Loader/XmlFileLoaderTest.php
  src/Symfony/Component/DependencyInjection/Tests/ParameterBag/EnvPlaceholderParameterBagTest.php
  src/Symfony/Component/Form/Tests/AbstractDivLayoutTest.php
  src/Symfony/Component/Form/Tests/AbstractLayoutTest.php
  src/Symfony/Component/Form/Tests/AbstractTableLayoutTest.php
  src/Symfony/Component/Form/Tests/Command/DebugCommandTest.php
  src/Symfony/Component/HttpFoundation/Tests/BinaryFileResponseTest.php
  src/Symfony/Component/HttpFoundation/Tests/RequestTest.php
  src/Symfony/Component/HttpFoundation/Tests/ResponseTest.php
  src/Symfony/Component/HttpKernel/Tests/EventListener/RouterListenerTest.php
  src/Symfony/Component/HttpKernel/Tests/UriSignerTest.php
  src/Symfony/Component/Process/Tests/PhpProcessTest.php
  src/Symfony/Component/Process/Tests/ProcessBuilderTest.php
  src/Symfony/Component/Yaml/Tests/Command/LintCommandTest.php
  src/Symfony/Component/Yaml/Tests/InlineTest.php
  src/Symfony/Component/Yaml/Tests/ParserTest.php
Labels: Bug, Status: Needs Review

#32969 Use assertContainsEquals when needed
  src/Symfony/Component/DependencyInjection/Tests/Compiler/MergeExtensionConfigurationPassTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/CountryTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/CurrencyTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/LanguageTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/LocaleTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/TimezoneTypeTest.php
  src/Symfony/Component/Security/Core/Tests/Authentication/Provider/UserAuthenticationProviderTest.php
Labels: Bug, Status: Needs Review

#32968 Use assertEqualsWithDelta when needed
  src/Symfony/Component/HttpFoundation/Tests/CookieTest.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php
  src/Symfony/Component/Stopwatch/Tests/StopwatchEventTest.php
Labels: Bug, Status: Needs Review

#32974 "An instance of X" phpdocs removal
  src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php
  src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php
  src/Symfony/Bundle/FrameworkBundle/Routing/Router.php
  src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
  src/Symfony/Bundle/TwigBundle/TemplateIterator.php
  src/Symfony/Bundle/WebProfilerBundle/DependencyInjection/WebProfilerExtension.php
  src/Symfony/Component/BrowserKit/CookieJar.php
  src/Symfony/Component/Console/Helper/ProgressBar.php
  src/Symfony/Component/Console/Helper/QuestionHelper.php
  src/Symfony/Component/ErrorHandler/FatalErrorHandler/FatalErrorHandlerInterface.php
  src/Symfony/Component/ExpressionLanguage/ParsedExpression.php
  src/Symfony/Component/HttpFoundation/Session/Session.php
  src/Symfony/Component/HttpKernel/Config/FileLocator.php
  src/Symfony/Component/HttpKernel/EventListener/FragmentListener.php
  src/Symfony/Component/HttpKernel/EventListener/LocaleListener.php
  src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php
  src/Symfony/Component/HttpKernel/EventListener/RouterListener.php
  src/Symfony/Component/HttpKernel/Fragment/AbstractSurrogateFragmentRenderer.php
  src/Symfony/Component/HttpKernel/Fragment/FragmentRendererInterface.php
  src/Symfony/Component/HttpKernel/Fragment/RoutableFragmentRenderer.php
  src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php
  src/Symfony/Component/HttpKernel/HttpCache/SurrogateInterface.php
  src/Symfony/Component/HttpKernel/HttpKernel.php
  src/Symfony/Component/HttpKernel/HttpKernelInterface.php
  src/Symfony/Component/Ldap/Adapter/AbstractConnection.php
  src/Symfony/Component/Routing/Loader/YamlFileLoader.php
  src/Symfony/Component/Routing/Router.php
  src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php
  src/Symfony/Component/Security/Core/Authorization/AccessDecisionManagerInterface.php
  src/Symfony/Component/Security/Core/Authorization/Voter/VoterInterface.php
  src/Symfony/Component/Security/Guard/Firewall/GuardAuthenticationListener.php
  src/Symfony/Component/Security/Http/AccessMap.php
  src/Symfony/Component/Security/Http/Authentication/CustomAuthenticationFailureHandler.php
  src/Symfony/Component/Security/Http/Authentication/CustomAuthenticationSuccessHandler.php
  src/Symfony/Component/Security/Http/EntryPoint/FormAuthenticationEntryPoint.php
  src/Symfony/Component/Security/Http/Firewall/LogoutListener.php
  src/Symfony/Component/Security/Http/HttpUtils.php
  src/Symfony/Component/Serializer/Normalizer/DenormalizerAwareTrait.php
  src/Symfony/Component/Serializer/Normalizer/NormalizerAwareTrait.php
  src/Symfony/Component/Serializer/SerializerAwareTrait.php
  src/Symfony/Component/Templating/Loader/CacheLoader.php
  src/Symfony/Component/Translation/Translator.php
  src/Symfony/Component/VarDumper/Dumper/AbstractDumper.php
Labels: Status: Needs Review

#31546 [Dotenv] Use default value when referenced variable is not set
  src/Symfony/Component/Dotenv/Dotenv.php
  src/Symfony/Component/Dotenv/Tests/DotenvTest.php
Labels: Dotenv, Feature, Status: Reviewed

#32649 [Security] Improve fa (persian) translation
  src/Symfony/Component/Security/Core/Resources/translations/security.fa.xlf
Labels: Status: Reviewed

#32555 [Lock] remove deprecated code
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  src/Symfony/Component/Lock/CHANGELOG.md
  src/Symfony/Component/Lock/Factory.php
  src/Symfony/Component/Lock/Lock.php
  src/Symfony/Component/Lock/LockFactory.php
  src/Symfony/Component/Lock/Store/CombinedStore.php
  src/Symfony/Component/Lock/Store/FlockStore.php
  src/Symfony/Component/Lock/Store/MemcachedStore.php
  src/Symfony/Component/Lock/Store/PdoStore.php
  src/Symfony/Component/Lock/Store/RedisStore.php
  src/Symfony/Component/Lock/Store/RetryTillSaveStore.php
  src/Symfony/Component/Lock/Store/SemaphoreStore.php
  src/Symfony/Component/Lock/Store/ZookeeperStore.php
  src/Symfony/Component/Lock/StoreInterface.php
  src/Symfony/Component/Lock/Tests/FactoryTest.php
  src/Symfony/Component/Lock/Tests/LockFactoryTest.php
  src/Symfony/Component/Lock/Tests/LockTest.php
Labels: Lock, Status: Reviewed

#32807 [HttpClient] add "max_duration" option
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
  src/Symfony/Bundle/FrameworkBundle/Resources/config/schema/symfony-1.0.xsd
  src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/Fixtures/php/http_client_full_default_options.php
  src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/Fixtures/xml/http_client_full_default_options.xml
  src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/Fixtures/yml/http_client_full_default_options.yml
  src/Symfony/Bundle/FrameworkBundle/Tests/DependencyInjection/FrameworkExtensionTest.php
  src/Symfony/Component/HttpClient/CHANGELOG.md
  src/Symfony/Component/HttpClient/CurlHttpClient.php
  src/Symfony/Component/HttpClient/HttpClientTrait.php
  src/Symfony/Component/HttpClient/NativeHttpClient.php
  src/Symfony/Component/HttpClient/Tests/MockHttpClientTest.php
  src/Symfony/Component/HttpClient/composer.json
  src/Symfony/Contracts/HttpClient/HttpClientInterface.php
  src/Symfony/Contracts/HttpClient/Test/Fixtures/web/index.php
  src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
Labels: Feature, HttpClient, Status: Reviewed

#32964 add yceruto as code owner of the ErrorRenderer component
  .github/CODEOWNERS
  src/Symfony/Component/ErrorRenderer/composer.json
Labels: Status: Reviewed

#32982 Ignore ErrorHandler DebugClassLoaderTest class in PHP-CS-Fixer config
  .php_cs.dist
Labels: Status: Needs Review

#32984 [HttpClient] Relax max duration test assertion
  src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
Labels: Bug, HttpClient, Status: Needs Review

#32990 [Lock] remove un-needed implements interface
  src/Symfony/Component/Lock/Store/FlockStore.php
Labels: Lock, Status: Reviewed

#32957 [Console] Check for ErrorHandler classes
  src/Symfony/Component/Console/Application.php
Labels: Bug, Console, Status: Reviewed

#32999 Added correct plural for box -> boxes
  src/Symfony/Component/Inflector/Inflector.php
  src/Symfony/Component/Inflector/Tests/InflectorTest.php
Labels: Bug, Inflector, Status: Reviewed

#32963 [Mailer] fix getName() when transport is null
  src/Symfony/Component/Mailer/Transport/AbstractTransport.php
  src/Symfony/Component/Mailer/Transport/SendmailTransport.php
Labels: Bug, Status: Reviewed

#32998 SCA: dropped unused mocks, duplicate import and a function alias usage
  src/Symfony/Component/Config/Tests/Definition/Builder/NumericNodeDefinitionTest.php
  src/Symfony/Component/ExpressionLanguage/Tests/ExpressionLanguageTest.php
  src/Symfony/Component/Ldap/Tests/LdapTestCase.php
  src/Symfony/Component/Security/Guard/Tests/GuardAuthenticatorHandlerTest.php
  src/Symfony/Component/Security/Http/Tests/Firewall/BasicAuthenticationListenerTest.php
  src/Symfony/Component/Security/Http/Tests/RememberMe/AbstractRememberMeServicesTest.php
  src/Symfony/Component/Translation/Tests/DependencyInjection/TranslationExtractorPassTest.php
Labels: Status: Needs Review

#32977 Remove deprecated assertContains
  src/Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler/DeprecationTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/CachePoolDeleteCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Command/XliffLintCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Console/ApplicationTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/CachePoolListCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ConfigDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/DebugAutowiringCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/RouterDebugCommandTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/TranslationDebugCommandTest.php
  src/Symfony/Bundle/SecurityBundle/Tests/Functional/UserPasswordEncoderCommandTest.php
  src/Symfony/Component/BrowserKit/Tests/HttpBrowserTest.php
  src/Symfony/Component/Config/Tests/Fixtures/Resource/.hiddenFile
  src/Symfony/Component/Console/Tests/ApplicationTest.php
  src/Symfony/Component/Debug/Tests/ExceptionHandlerTest.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/CustomExpressionLanguageFunctionTest.php
  src/Symfony/Component/Form/Tests/Command/DebugCommandTest.php
  src/Symfony/Component/HttpFoundation/Tests/Test/Constraint/ResponseIsRedirectedTest.php
  src/Symfony/Component/HttpFoundation/Tests/Test/Constraint/ResponseIsSuccessfulTest.php
  src/Symfony/Component/HttpFoundation/Tests/Test/Constraint/ResponseStatusCodeSameTest.php
  src/Symfony/Component/HttpKernel/Tests/HttpKernelTest.php
  src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php
  src/Symfony/Component/Mailer/Tests/TransportTest.php
  src/Symfony/Component/Messenger/Tests/Command/ConsumeMessagesCommandTest.php
  src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRemoveCommandTest.php
  src/Symfony/Component/Messenger/Tests/Command/FailedMessagesRetryCommandTest.php
  src/Symfony/Component/Messenger/Tests/Command/FailedMessagesShowCommandTest.php
  src/Symfony/Component/Messenger/Tests/Command/SetupTransportsCommandTest.php
  src/Symfony/Component/Mime/Tests/EmailTest.php
  src/Symfony/Component/Mime/Tests/Part/MessagePartTest.php
  src/Symfony/Component/Translation/Tests/Command/XliffLintCommandTest.php
  src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
Labels: Feature, Status: Needs Review

#32989 [HttpClient] Declare `$active` first to prevent weird issue
  src/Symfony/Component/HttpClient/CurlHttpClient.php
  src/Symfony/Component/HttpClient/Response/CurlResponse.php
Labels: Bug, Status: Reviewed

#32992 [ProxyManagerBridge] Polyfill for unmaintained version
  composer.json
  src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php
  src/Symfony/Bridge/ProxyManager/Legacy/ProxiedMethodReturnExpression.php
  src/Symfony/Bridge/ProxyManager/Tests/LazyProxy/PhpDumper/ProxyDumperTest.php
  src/Symfony/Bridge/ProxyManager/composer.json
Labels: Bug, ProxyManagerBridge, Status: Reviewed

#32986 [Mime] fixed wrong mimetype
  src/Symfony/Component/Mime/MimeTypes.php
  src/Symfony/Component/Mime/Resources/bin/update_mime_types.php
Labels: Bug, Mime, Status: Reviewed

#33009 Fix inconsistent return points
  src/Symfony/Bridge/Monolog/Logger.php
  src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php
  src/Symfony/Component/Console/Terminal.php
  src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php
  src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php
  src/Symfony/Component/HttpKernel/HttpCache/Store.php
  src/Symfony/Component/PropertyAccess/PropertyAccessor.php
  src/Symfony/Component/Routing/Loader/XmlFileLoader.php
  src/Symfony/Component/Serializer/Serializer.php
Labels: Bug, Status: Reviewed

#32981 Fix tests/code for php 7.4
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php
  src/Symfony/Component/Config/Util/XmlUtils.php
  src/Symfony/Component/Debug/ErrorHandler.php
  src/Symfony/Component/Debug/Tests/ErrorHandlerTest.php
  src/Symfony/Component/DomCrawler/FormFieldRegistry.php
  src/Symfony/Component/Finder/Tests/Iterator/SortableIteratorTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/DateTypeTest.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractCurrencyDataProviderTest.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractLanguageDataProviderTest.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractLocaleDataProviderTest.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractRegionDataProviderTest.php
  src/Symfony/Component/Intl/Tests/Data/Provider/AbstractScriptDataProviderTest.php
  src/Symfony/Component/Intl/Tests/DateFormatter/AbstractIntlDateFormatterTest.php
  src/Symfony/Component/Intl/Tests/IntlTest.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php
  src/Symfony/Component/Stopwatch/Tests/StopwatchTest.php
  src/Symfony/Component/Translation/Loader/CsvFileLoader.php
  src/Symfony/Component/Translation/Tests/IdentityTranslatorTest.php
  src/Symfony/Component/Validator/Tests/Constraints/CountryValidatorTest.php
  src/Symfony/Component/Validator/Tests/Constraints/CurrencyValidatorTest.php
  src/Symfony/Component/Validator/Tests/Constraints/LanguageValidatorTest.php
  src/Symfony/Component/Validator/Tests/Constraints/RangeValidatorTest.php
  src/Symfony/Component/VarDumper/Tests/Caster/ExceptionCasterTest.php
Labels: Bug, Status: Reviewed

#33010 [TwigBridge] pass translation parameters to the trans filter
  src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig
  src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig
  src/Symfony/Bridge/Twig/Resources/views/Form/foundation_5_layout.html.twig
Labels: Bug, Status: Reviewed, TwigBridge

#33007 Fix some return type annotations
  src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor.php
  src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/XmlDescriptor.php
  src/Symfony/Component/Console/Descriptor/JsonDescriptor.php
  src/Symfony/Component/Console/Descriptor/XmlDescriptor.php
  src/Symfony/Component/DomCrawler/Crawler.php
  src/Symfony/Component/Form/NativeRequestHandler.php
  src/Symfony/Component/HttpKernel/HttpCache/Store.php
Labels: Bug, Status: Reviewed

#33013 [ErrorRenderer] Fix timestamp on logs view
  src/Symfony/Component/ErrorRenderer/Resources/views/logs.html.php
Labels: Bug, ErrorRenderer, Status: Reviewed

#32516 [FrameworkBundle][Config] Ignore exceptions thrown during reflection classes autoload
  src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AbstractPhpFileCacheWarmer.php
  src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php
  src/Symfony/Bundle/FrameworkBundle/CacheWarmer/SerializerCacheWarmer.php
  src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ValidatorCacheWarmer.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/AnnotationsCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/SerializerCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/ValidatorCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Serialization/Resources/does_not_exist.yaml
  src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Validation/Resources/does_not_exist.yaml
  src/Symfony/Bundle/FrameworkBundle/composer.json
  src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php
  src/Symfony/Component/Config/Resource/ClassExistenceResource.php
Labels: Bug, FrameworkBundle, Status: Reviewed

#33011 [5.0][HttpKernel] reintroduce __wakeup method in DataCollector
  src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php
Labels: Bug, HttpKernel, Status: Reviewed

#33021 [FrameworkBundle] remove deprecated cache pool argument
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/AnnotationsCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/SerializerCacheWarmerTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/ValidatorCacheWarmerTest.php
Labels: FrameworkBundle, Status: Reviewed

#33022 [HttpClient] Remove CURLOPT_CONNECTTIMEOUT_MS curl opt
  src/Symfony/Component/HttpClient/CurlHttpClient.php
  src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
Labels: Bug, HttpClient, Status: Reviewed

#33032 [Ldap] remove wrongly added legacy group from test
  src/Symfony/Component/Ldap/Tests/Security/LdapUserProviderTest.php
Labels: Ldap, Status: Reviewed

#33034 [Cache] Remove PhpArrayAdapter::throwOnRequiredClass()
  src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php
Labels: Cache, Status: Needs Review

#33036 [Debug] Improve UPGRADE files
  UPGRADE-4.4.md
  UPGRADE-5.0.md
Labels: Debug, Status: Needs Review

#33035 [Lock] Fix return typehint
  src/Symfony/Component/Lock/Lock.php
Labels: Bug, Lock, Status: Reviewed

#33033 [Lock] consistently throw NotSupportException
  src/Symfony/Component/Lock/Store/CombinedStore.php
  src/Symfony/Component/Lock/Store/MemcachedStore.php
  src/Symfony/Component/Lock/Store/RedisStore.php
Labels: Lock, Status: Reviewed

#33031 [HttpKernel] Clarify error handler restoring process again
  src/Symfony/Component/HttpKernel/Kernel.php
Labels: HttpKernel, Status: Reviewed

#33030 [Console] add missing conflict rule
  src/Symfony/Component/Console/composer.json
Labels: Bug, Console, Status: Reviewed

#33029 [Lock] remove deprecated waitAndSave() methods
  src/Symfony/Component/Lock/CHANGELOG.md
  src/Symfony/Component/Lock/Store/CombinedStore.php
  src/Symfony/Component/Lock/Store/MemcachedStore.php
  src/Symfony/Component/Lock/Store/RedisStore.php
  src/Symfony/Component/Lock/Store/ZookeeperStore.php
Labels: BC Break, Lock, Status: Reviewed

#33016 [HttpKernel] Resilience against file_get_contents() race conditions
  src/Symfony/Component/HttpKernel/HttpCache/Store.php
Labels: Bug, HttpKernel, Status: Reviewed

#33027 Drop Debug compatibility layers
  src/Symfony/Bridge/ProxyManager/Legacy/ProxiedMethodReturnExpression.php
  src/Symfony/Component/Console/Application.php
  src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php
Labels: Status: Reviewed

#33020 [Intl] fix nullable phpdocs and useless method visibility of internal class
  src/Symfony/Component/Intl/Collator/Collator.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/FullTransformer.php
  src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php
  src/Symfony/Component/Intl/NumberFormatter/NumberFormatter.php
Labels: Intl, Status: Reviewed

#33040 [Console] Fix parse error
  src/Symfony/Component/Console/Application.php
Labels: Bug, Console, Status: Reviewed

#33018 remove some more useless phpdocs
  src/Symfony/Component/HttpKernel/EventListener/LocaleListener.php
  src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php
  src/Symfony/Component/HttpKernel/HttpKernel.php
  src/Symfony/Component/Intl/Data/Bundle/Writer/TextBundleWriter.php
  src/Symfony/Component/Security/Http/Firewall/LogoutListener.php
Labels: Status: Reviewed

#33045 Make HttpClientTestCase compatible with PHPUnit8
  src/Symfony/Contracts/HttpClient/Test/HttpClientTestCase.php
Labels: Bug, Status: Needs Review

#33000 Fix deprecations on 4.3
  .travis.yml
  src/Symfony/Bridge/ProxyManager/Tests/LazyProxy/PhpDumper/Fixtures/proxy-implem.php
  src/Symfony/Bridge/ProxyManager/Tests/LazyProxy/PhpDumper/ProxyDumperTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Functional/ContainerDebugCommandTest.php
  src/Symfony/Bundle/SecurityBundle/Tests/Functional/UserPasswordEncoderCommandTest.php
  src/Symfony/Component/Cache/Tests/Adapter/AdapterTestCase.php
  src/Symfony/Component/Config/Tests/Definition/Builder/NodeDefinitionTest.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php
  src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/CountryTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/CurrencyTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/LanguageTypeTest.php
  src/Symfony/Component/Form/Tests/Extension/Core/Type/LocaleTypeTest.php
  src/Symfony/Component/Mailer/Tests/Transport/AbstractTransportTest.php
  src/Symfony/Component/Messenger/Tests/Handler/HandlersLocatorTest.php
  src/Symfony/Component/Messenger/Tests/Middleware/ActivationMiddlewareTest.php
  src/Symfony/Component/Messenger/Tests/Middleware/HandleMessageMiddlewareTest.php
  src/Symfony/Component/Messenger/Tests/Transport/Doctrine/DoctrineSenderTest.php
  src/Symfony/Component/Messenger/Tests/Transport/Serialization/PhpSerializerTest.php
  src/Symfony/Component/Messenger/Tests/Transport/Serialization/SerializerTest.php
  src/Symfony/Component/Messenger/Transport/Sync/SyncTransport.php
  src/Symfony/Component/VarDumper/Tests/Cloner/VarClonerTest.php
  src/Symfony/Component/VarExporter/Tests/VarExporterTest.php
Labels: Bug, Status: Reviewed

#33055 [FrameworkBundle][TwigBridge] Fix test compatibility with 4.x components
  src/Symfony/Bridge/Twig/Tests/Extension/FormExtensionBootstrap3HorizontalLayoutTest.php
  src/Symfony/Bridge/Twig/Tests/Extension/FormExtensionBootstrap3LayoutTest.php
  src/Symfony/Bridge/Twig/Tests/Extension/FormExtensionBootstrap4HorizontalLayoutTest.php
  src/Symfony/Bridge/Twig/Tests/Extension/FormExtensionBootstrap4LayoutTest.php
  src/Symfony/Bridge/Twig/Tests/Extension/FormExtensionDivLayoutTest.php
  src/Symfony/Bridge/Twig/Tests/Extension/FormExtensionTableLayoutTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/FormHelperDivLayoutTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/FormHelperTableLayoutTest.php
Labels: Bug, FrameworkBundle, Status: Reviewed, TwigBridge

#32800 Improve some URLs
  src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php
  src/Symfony/Bridge/Twig/Extension/CodeExtension.php
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  src/Symfony/Bundle/FrameworkBundle/Templating/Helper/CodeHelper.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Controller/ControllerTraitTest.php
  src/Symfony/Bundle/WebServerBundle/Command/ServerRunCommand.php
  src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php
  src/Symfony/Bundle/WebServerBundle/Resources/router.php
  src/Symfony/Component/Console/Command/Command.php
  src/Symfony/Component/Console/Input/ArgvInput.php
  src/Symfony/Component/Console/Logger/ConsoleLogger.php
  src/Symfony/Component/Debug/Tests/ExceptionHandlerTest.php
  src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php
  src/Symfony/Component/EventDispatcher/Tests/AbstractEventDispatcherTest.php
  src/Symfony/Component/Filesystem/Filesystem.php
  src/Symfony/Component/Filesystem/Tests/FilesystemTestCase.php
  src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php
  src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php
  src/Symfony/Component/Form/Extension/Core/Type/BaseType.php
  src/Symfony/Component/Form/Extension/Core/Type/DateType.php
  src/Symfony/Component/HttpFoundation/CHANGELOG.md
  src/Symfony/Component/HttpFoundation/File/MimeType/FileinfoMimeTypeGuesser.php
  src/Symfony/Component/HttpFoundation/JsonResponse.php
  src/Symfony/Component/HttpFoundation/ParameterBag.php
  src/Symfony/Component/HttpFoundation/RedirectResponse.php
  src/Symfony/Component/HttpFoundation/Request.php
  src/Symfony/Component/HttpFoundation/Response.php
  src/Symfony/Component/HttpFoundation/ServerBag.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MongoDbSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php
  src/Symfony/Component/HttpFoundation/Session/Storage/SessionStorageInterface.php
  src/Symfony/Component/HttpKernel/EventListener/SaveSessionListener.php
  src/Symfony/Component/HttpKernel/Profiler/Profiler.php
  src/Symfony/Component/Intl/Collator/Collator.php
  src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php
  src/Symfony/Component/Intl/Data/Util/ArrayAccessibleResourceBundle.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/TimezoneTransformer.php
  src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php
  src/Symfony/Component/Intl/Locale/Locale.php
  src/Symfony/Component/Intl/NumberFormatter/NumberFormatter.php
  src/Symfony/Component/Intl/README.md
  src/Symfony/Component/Process/Pipes/WindowsPipes.php
  src/Symfony/Component/Process/Process.php
  src/Symfony/Component/Process/ProcessUtils.php
  src/Symfony/Component/Process/Tests/ProcessTest.php
  src/Symfony/Component/Serializer/Encoder/JsonDecode.php
  src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php
  src/Symfony/Component/Validator/Constraints/AbstractComparisonValidator.php
  src/Symfony/Component/Validator/Constraints/RangeValidator.php
  src/Symfony/Component/Validator/Tests/Constraints/IpValidatorTest.php
  src/Symfony/Component/VarDumper/Caster/DateCaster.php
  src/Symfony/Component/Workflow/Dumper/GraphvizDumper.php
Labels: Status: Reviewed

#33058 [HttpClient] fix data loss when streaming as a PHP resource
  src/Symfony/Component/HttpClient/Response/StreamWrapper.php
Labels: Bug, HttpClient, Status: Needs Review

#33056 cleanup remaining param $options and internal Intl FullTransformer
  src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php
  src/Symfony/Bundle/FrameworkBundle/Routing/Router.php
  src/Symfony/Bundle/FrameworkBundle/Templating/Helper/ActionsHelper.php
  src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php
  src/Symfony/Component/Cache/Traits/MemcachedTrait.php
  src/Symfony/Component/Console/Descriptor/DescriptorInterface.php
  src/Symfony/Component/Console/Formatter/OutputFormatterStyle.php
  src/Symfony/Component/Console/Helper/DescriptorHelper.php
  src/Symfony/Component/DependencyInjection/Dumper/DumperInterface.php
  src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php
  src/Symfony/Component/Form/Tests/AbstractFormTest.php
  src/Symfony/Component/Form/Tests/CompoundFormTest.php
  src/Symfony/Component/Form/Tests/SimpleFormTest.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MongoDbSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.php
  src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php
  src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php
  src/Symfony/Component/HttpKernel/Fragment/FragmentRendererInterface.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/FullTransformer.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/Transformer.php
  src/Symfony/Component/Process/Tests/ProcessTest.php
  src/Symfony/Component/Routing/Generator/Dumper/GeneratorDumperInterface.php
  src/Symfony/Component/Routing/Matcher/Dumper/MatcherDumperInterface.php
  src/Symfony/Component/Routing/Route.php
  src/Symfony/Component/Routing/RouteCollection.php
  src/Symfony/Component/Routing/Router.php
  src/Symfony/Component/Workflow/Dumper/DumperInterface.php
Labels: Status: Reviewed

#33059 [Console] add missing type hints
  src/Symfony/Component/Console/Helper/DescriptorHelper.php
  src/Symfony/Component/Console/Helper/ProgressIndicator.php
  src/Symfony/Component/Console/Helper/TableStyle.php
Labels: Console, Status: Reviewed

#33051 [HttpKernel] Fix s-maxage=3 transient test
  src/Symfony/Component/HttpKernel/Tests/HttpCache/HttpCacheTest.php
Labels: Bug, HttpKernel, Status: Needs Review

#32525 [Intl][5.0] Add parameters type-hints
  src/Symfony/Component/Intl/Collator/Collator.php
  src/Symfony/Component/Intl/Data/Bundle/Compiler/BundleCompilerInterface.php
  src/Symfony/Component/Intl/Data/Bundle/Compiler/GenrbCompiler.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/BufferedBundleReader.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReaderInterface.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/BundleReaderInterface.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/IntlBundleReader.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/JsonBundleReader.php
  src/Symfony/Component/Intl/Data/Bundle/Reader/PhpBundleReader.php
  src/Symfony/Component/Intl/Data/Bundle/Writer/BundleWriterInterface.php
  src/Symfony/Component/Intl/Data/Bundle/Writer/JsonBundleWriter.php
  src/Symfony/Component/Intl/Data/Bundle/Writer/PhpBundleWriter.php
  src/Symfony/Component/Intl/Data/Bundle/Writer/TextBundleWriter.php
  src/Symfony/Component/Intl/Data/Generator/AbstractDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/CurrencyDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/FallbackTrait.php
  src/Symfony/Component/Intl/Data/Generator/GeneratorConfig.php
  src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/LocaleDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/ScriptDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/TimezoneDataGenerator.php
  src/Symfony/Component/Intl/Data/Util/LocaleScanner.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/FullTransformer.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/Hour1200Transformer.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/Hour2400Transformer.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/Hour2401Transformer.php
  src/Symfony/Component/Intl/DateFormatter/DateFormat/TimezoneTransformer.php
  src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php
  src/Symfony/Component/Intl/Globals/IntlGlobals.php
  src/Symfony/Component/Intl/Locale.php
  src/Symfony/Component/Intl/Locale/Locale.php
  src/Symfony/Component/Intl/NumberFormatter/NumberFormatter.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php
  src/Symfony/Component/Intl/Tests/NumberFormatter/NumberFormatterTest.php
  src/Symfony/Component/Intl/Util/IcuVersion.php
  src/Symfony/Component/Intl/Util/Version.php
Labels: Intl, Status: Reviewed

#32122 [HttpFoundation] deprecate HeaderBag::get() returning an array and add all($key) instead
  UPGRADE-4.4.md
  UPGRADE-5.0.md
  src/Symfony/Component/HttpFoundation/CHANGELOG.md
  src/Symfony/Component/HttpFoundation/HeaderBag.php
  src/Symfony/Component/HttpFoundation/Response.php
  src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php
  src/Symfony/Component/HttpFoundation/Test/Constraint/ResponseHeaderSame.php
  src/Symfony/Component/HttpFoundation/Tests/HeaderBagTest.php
  src/Symfony/Component/HttpFoundation/Tests/ResponseHeaderBagTest.php
  src/Symfony/Component/HttpKernel/Tests/EventListener/TestSessionListenerTest.php
  src/Symfony/Component/WebLink/Tests/EventListener/AddLinkHeaderListenerTest.php
  src/Symfony/Component/WebLink/composer.json
Labels: Feature, HttpFoundation, Status: Reviewed

#33048 Remove ForwardCompatTestTrait
  src/Symfony/Bundle/FrameworkBundle/Test/ForwardCompatTestTrait.php
  src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php
  src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php
  src/Symfony/Component/Form/Test/FormIntegrationTestCase.php
  src/Symfony/Component/Form/Test/ForwardCompatTestTrait.php
  src/Symfony/Component/Form/Test/TypeTestCase.php
  src/Symfony/Component/Validator/Test/ConstraintValidatorTestCase.php
  src/Symfony/Component/Validator/Test/ForwardCompatTestTrait.php
Labels: BC Break, Status: Reviewed

#33068 Fix tests deprecation in 4.4 branch
  src/Symfony/Component/ErrorRenderer/Tests/Exception/FlattenExceptionTest.php
  src/Symfony/Component/Mime/Tests/Crypto/SMimeTestCase.php
Labels: Bug, Status: Reviewed

#33069 Replace warning by isolated test
  src/Symfony/Bundle/FrameworkBundle/Tests/CacheWarmer/ValidatorCacheWarmerTest.php
  src/Symfony/Component/Config/Tests/Resource/ClassExistenceResourceTest.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/AutowirePassTest.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveBindingsPassTest.php
  src/Symfony/Component/DependencyInjection/Tests/Dumper/PhpDumperTest.php
  src/Symfony/Component/DependencyInjection/Tests/Loader/FileLoaderTest.php
Labels: Bug, Status: Needs Review

#33067 [VarDumper] Fix test patern to handle callstack with/without return typehint
  src/Symfony/Component/VarDumper/Tests/Caster/ReflectionCasterTest.php
Labels: Bug, Status: Needs Review, VarDumper

#33071 Fix deprecation test on master
  src/Symfony/Bundle/FrameworkBundle/Tests/Controller/AbstractControllerTest.php
Labels: Bug, Status: Needs Review

#33057 [HttpKernel] Lower EOL date
  src/Symfony/Component/HttpKernel/Kernel.php
Labels: Bug, HttpKernel, Status: Reviewed

#33066 [Serializer] Fix negative DateInterval
  src/Symfony/Component/Serializer/Normalizer/DateIntervalNormalizer.php
  src/Symfony/Component/Serializer/Tests/Normalizer/DateIntervalNormalizerTest.php
Labels: Bug, Serializer, Status: Reviewed

#31083 [Validator] Allow objects implementing __toString() to be used as violation messages
  src/Symfony/Component/Validator/CHANGELOG.md
  src/Symfony/Component/Validator/ConstraintViolation.php
  src/Symfony/Component/Validator/ConstraintViolationInterface.php
  src/Symfony/Component/Validator/Context/ExecutionContextInterface.php
  src/Symfony/Component/Validator/Tests/ConstraintViolationTest.php
  src/Symfony/Component/Validator/Violation/ConstraintViolationBuilder.php
Labels: Feature, Status: Reviewed, Validator

#32486 [DoctrineBridge] Invokable event listeners
  src/Symfony/Bridge/Doctrine/CHANGELOG.md
  src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php
  src/Symfony/Bridge/Doctrine/Tests/ContainerAwareEventManagerTest.php
Labels: DoctrineBridge, Feature, Status: Reviewed

#32598 [FrameworkBundle][Routing] Private service route loaders
  UPGRADE-4.4.md
  UPGRADE-5.0.md
  src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/UnusedTagsPass.php
  src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php
  src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php
  src/Symfony/Bundle/FrameworkBundle/Resources/config/routing.xml
  src/Symfony/Bundle/FrameworkBundle/Routing/LegacyRouteLoaderContainer.php
  src/Symfony/Bundle/FrameworkBundle/Routing/RouteLoaderInterface.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Kernel/MicroKernelTraitTest.php
  src/Symfony/Bundle/FrameworkBundle/Tests/Routing/LegacyRouteLoaderContainerTest.php
Labels: Ready, Status: Reviewed

#33080 Update UPGRADE file to indicate method signature changed
  UPGRADE-4.4.md
  UPGRADE-5.0.md
  src/Symfony/Bundle/FrameworkBundle/CHANGELOG.md
  src/Symfony/Component/Form/CHANGELOG.md
  src/Symfony/Component/Validator/CHANGELOG.md
Labels: Deprecation, Status: Needs Review

#32988 [Intl] Support ISO 3166-1 Alpha-3 country codes
  src/Symfony/Component/Intl/CHANGELOG.md
  src/Symfony/Component/Intl/Countries.php
  src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php
  src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php
  src/Symfony/Component/Intl/Languages.php
  src/Symfony/Component/Intl/Resources/data/languages/meta.json
  src/Symfony/Component/Intl/Resources/data/regions/meta.json
  src/Symfony/Component/Intl/Tests/CountriesTest.php
  src/Symfony/Component/Intl/Tests/LanguagesTest.php
Labels: Feature, Status: Reviewed

#33083 Added the missing translations for the Slovak 'sk' locale.
  src/Symfony/Component/Validator/Resources/translations/validators.sk.xlf
Labels: Bug, Status: Reviewed

#33078 Add compatibility trait for PHPUnit constraint classes
  src/Symfony/Bridge/PhpUnit/ConstraintTrait.php
  src/Symfony/Bridge/PhpUnit/Legacy/ConstraintTraitForV6.php
  src/Symfony/Bridge/PhpUnit/Legacy/ConstraintTraitForV7.php
Labels: Feature, Status: Reviewed

#33085 [Validator] fix Danish translations
  src/Symfony/Component/Form/Resources/translations/validators.da.xlf
  src/Symfony/Component/Validator/Resources/translations/validators.da.xlf
Labels: Bug, Status: Reviewed, Validator

#33087 Fix unitialized variable in DeprecationErrorHandler
  src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php
Labels: Bug, Status: Reviewed

#32541 [HttpKernel] trim the leading backslash in the controller init
  src/Symfony/Component/HttpKernel/Tests/Controller/ContainerControllerResolverTest.php
  src/Symfony/Component/HttpKernel/Tests/Controller/ControllerResolverTest.php
Labels: HttpKernel, Status: Reviewed

#33092 [DependencyInjection] Improve an exception message
  src/Symfony/Component/DependencyInjection/Compiler/ResolveClassPass.php
  src/Symfony/Component/DependencyInjection/Tests/Compiler/ResolveClassPassTest.php
Labels: Bug, DependencyInjection, Status: Reviewed

#33093 [EventDispatcher] wrong Request class
  src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php
Labels: Bug, EventDispatcher, Status: Reviewed

#33097 Added translations in validator for Serbian Latin
  src/Symfony/Component/Validator/Resources/translations/validators.sr_Latn.xlf
Labels: Status: Reviewed

#33096 Added translations in validator for Serbian Cyrillic
  src/Symfony/Component/Validator/Resources/translations/validators.sr_Cyrl.xlf
Labels: Status: Reviewed

#33102 [Translation] Highlight invalid translation status
  src/Symfony/Component/Translation/Resources/bin/translation-status.php
Labels: Bug, Status: Reviewed, Translator
